general {
    lock_cmd = pidof hyprlock || hyprlock  
    before_sleep_cmd = pidof hyprlock || hyprlock  
    after_resume_cmd = hyprctl dispatch dpms on 
}

# NOTE: I commented the listeners out because they were causing problems where I couldn't wake my systems back up.
# TODO: solve issues with drivers not waking GPUs back up

# Locks computer after timeout period
#listener {
#    timeout = 300 
#    on-timeout = hyprlock 
#}

# Sleeps monitors after timeout period
#listener {
#    timeout = 600  
#    on-timeout = hyprctl dispatch dpms off  
#    on-resume = hyprctl dispatch dpms on  
#}
